from sqlalchemy import Column, Integer, String, DateTime, DECIMAL, Text, Boolean

from .database import Base


class CDP(Base):
    __tablename__ = "cdp"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    numero_documento = Column(Integer)
    fecha_registro = Column(DateTime)
    fecha_creacion = Column(DateTime)
    tipo_cdp = Column(String(50))
    estado = Column(String(50))
    dependencia = Column(String(50))
    dependencia_descripcion = Column(String(255))
    rubro = Column(String(100))
    descripcion = Column(String(500))
    fuente = Column(String(100))
    recurso = Column(String(100))
    sit = Column(String(50))
    valor_inicial = Column(DECIMAL(18, 2))
    valor_operaciones = Column(DECIMAL(18, 2))
    valor_actual = Column(DECIMAL(18, 2))
    saldo_por_comprometer = Column(DECIMAL(18, 2))
    objeto = Column(String(500))
    solicitud_cdp = Column(Integer)


class CRP(Base):
    __tablename__ = "crp"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    numero_documento = Column(Integer)
    fecha_registro = Column(DateTime)
    fecha_creacion = Column(DateTime)
    estado = Column(String(50))
    dependencia = Column(String(50))
    dependencia_descripcion = Column(String(255))
    rubro = Column(String(100))
    descripcion = Column(String(500))
    fuente = Column(String(100))
    recurso = Column(String(100))
    situacion = Column(String(50))
    valor_inicial = Column(DECIMAL(18, 2))
    valor_operaciones = Column(DECIMAL(18, 2))
    valor_actual = Column(DECIMAL(18, 2))
    saldo_por_utilizar = Column(DECIMAL(18, 2))
    tipo_identificacion = Column(String(50))
    identificacion = Column(String(50))
    nombre_razon_social = Column(String(255))
    medio_de_pago = Column(String(100))
    tipo_cuenta = Column(String(50))
    numero_cuenta = Column(String(50))
    estado_cuenta = Column(String(50))
    entidad_nit = Column(String(20))
    entidad_descripcion = Column(String(255))
    solicitud_cdp = Column(Integer)
    cdp = Column(Integer)
    compromisos = Column(Text)
    cuentas_por_pagar = Column(Text)
    obligaciones = Column(Text)
    ordenes_de_pago = Column(Text)
    reintegros = Column(Text)
    fecha_documento_soporte = Column(DateTime)
    tipo_documento_soporte = Column(String(100))
    numero_documento_soporte = Column(String(100))
    observaciones = Column(Text)


class Eje(Base):
    __tablename__ = "eje"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    dependecia_de_afectacion_de_gastos = Column(String(255))
    tipo = Column(String(5))
    cta = Column(String(10))
    subc = Column(String(10))
    objg = Column(String(10))
    ord = Column(String(10))
    sord = Column(String(10))
    item = Column(String(10))
    sitem = Column(String(10))
    concepto = Column(String(255))
    fuente = Column(String(50))
    situacion = Column(String(50))
    rec = Column(Integer)
    recurso = Column(String(100))
    es_resumen = Column(Boolean)
    apropiacion_vigente_dep_gsto = Column(DECIMAL(18, 2))
    total_cdp_dep_gstos = Column(DECIMAL(18, 2))
    apropiacion_disponible_dep_gsto = Column(DECIMAL(18, 2))
    total_cdp_modificacion_dep_gstos = Column(DECIMAL(18, 2))
    total_compromiso_dep_gstos = Column(DECIMAL(18, 2))
    cdp_por_comprometer_dep_gstos = Column(DECIMAL(18, 2))
    total_obligaciones_dep_gstos = Column(DECIMAL(18, 2))
    compromiso_por_obligar_dep_gstos = Column(DECIMAL(18, 2))
    total_ordenes_pago_dep_gstos = Column(DECIMAL(18, 2))
    obligaciones_por_ordenar_dep_gstos = Column(DECIMAL(18, 2))
    pagos_dep_gstos = Column(DECIMAL(18, 2))
    ordenes_pago_por_pagar_dep_gstos = Column(DECIMAL(18, 2))
    total_reintegros_dep_gstos = Column(DECIMAL(18, 2))
